---
dependency:
  name: galaxy
  options:
    role-file: meta/expanded_requirements.yml
    force: true

driver:
  name: docker

platforms:
  - name: tomcat9
    image: centos:7
    command: ""
    cgroupns_mode: host
    privileged: true

  - name: tomcat10
    image: centos:7
    command: ""
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
  inventory:
    links:
      host_vars: ../resources/inventory/host_vars/
  playbooks:
    converge: ../resources/converge.yml
  env:
    ANSIBLE_VERBOSITY: "1"
verifier:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: "1"

lint: |
  set -e
  yamllint .
  ansible-lint .
