---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  name: centos7
  test_sequence:
    - destroy
    - syntax
    - create
    - converge
    - destroy

platforms:
  - name: instance
    image: centos:7
    command: ""
    cgroupns_mode: host
    privileged: true

provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      callbacks_enabled: profile_tasks, timer, yaml
  playbooks:
    converge: ../resources/converge.yml
  env:
    ANSIBLE_VERBOSITY: "1"
verifier:
  name: ansible
  env:
    ANSIBLE_VERBOSITY: "1"

lint: |
  set -e
  yamllint .
  ansible-lint .
