name: Molecule Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        molecule_scenario:
          - centos7
          - rocky8
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
    steps:
      - name: Run `molecule test`
        uses: UCL-MIRSG/.github/actions/molecule-test@v0.25.0
        with:
          scenario: ${{ matrix.molecule_scenario }}
